version: "3.8"

services:
  mes:
    container_name: mes
    build: ./
    image: "mervin16/mes:1.2.1"
    networks:
      - mes_net
    expose:
      - 8089
    restart: always

  nginx_mes:
    image: nginx
    container_name: nginx_mes
    ports:
      - "8089:80"
    networks:
      - mes_net
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./log/nginx:/var/log/nginx
    depends_on:
      - mes
    restart: always

networks:
  mes_net:
    name: mes_network
    driver: bridge
